### PR TITLE
Bump base image and dependencies

### PR DESCRIPTION
**Pull request by casell**
1. Bumped base image from buster to bullseye
2. Updated installed dependencies
3. Minor change to remove cache

### CODE REVIEW

**Comment by casell** [comment]
Rebased after 2.22.0 addition in master

**Comment by casell** [comment]
@qoricode are you accepting this kind of PRs? If something is missing let me know, if you're not accepting PRs at all, feel free to close.

**Comment by qoricode** [comment]
Hi yes I'll give it a quick test.

**Comment by qoricode** [comment]
@casell Please update tags.csv to use the new jdk image for 2.22.0

**Comment by casell** [comment]
Do you mean 11.0.15-jre-bullseye?

Would you prefer only for 2.22.0 or for all?

**Comment by qoricode** [comment]
Yes just 2.22.0 will do!

**Comment by casell** [comment]
Done!

**Comment by qoricode** [comment]
@casell all seems OK thanks. I'll add a docker image for it as latest but with a new tag 2.22.0-jdk11.0.15 and revert to the version number alone with 2.23.0 or whatever comes next.

**Comment by casell** [comment]
> @casell all seems OK thanks. I'll add a docker image for it as latest but with a new tag 2.22.0-jdk11.0.15 and revert to the version number alone with 2.23.0 or whatever comes next.

Seems a good plan 😁

Thanks!

**Pull request merged**
